In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
ds = pd.read_csv("train.csv")

In [3]:
ds

date_time  deg_C  relative_humidity  absolute_humidity  \
0     2010-03-10 18:00:00   13.1               46.0             0.7578   
1     2010-03-10 19:00:00   13.2               45.3             0.7255   
2     2010-03-10 20:00:00   12.6               56.2             0.7502   
3     2010-03-10 21:00:00   11.0               62.4             0.7867   
4     2010-03-10 22:00:00   11.9               59.0             0.7888   
...                   ...    ...                ...                ...   
7106  2010-12-31 20:00:00    9.2               32.0             0.3871   
7107  2010-12-31 21:00:00    9.1               33.2             0.3766   
7108  2010-12-31 22:00:00    9.6               34.6             0.4310   
7109  2010-12-31 23:00:00    8.0               40.7             0.4085   
7110  2011-01-01 00:00:00    8.0               41.3             0.4375   

      sensor_1  sensor_2  sensor_3  sensor_4  sensor_5  \
0       1387.2    1087.8    1056.0    1742.8    1293.4   
1       1279.1     888.2    1197.5    1449.9    1010.9   
2       1331.9     929.6    1060.2    1586.1    1117.0   
3       1321.0     929.0    1102.9    1536.5    1263.2   
4       1272.0     852.7    1180.9    1415.5    1132.2   
...        ...       ...       ...       ...       ...   
7106    1000.5     811.2     873.0     909.0     910.5   
7107    1022.7     790.0     951.6     912.9     903.4   
7108    1044.4     767.3     861.9     889.2    1159.1   
7109     952.8     691.9     908.5     917.0    1206.3   
7110    1108.8     745.7     797.1     880.0    1273.1   

      target_carbon_monoxide  target_benzene  target_nitrogen_oxides  
0                        2.5            12.0                   167.7  
1                        2.1             9.9                    98.9  
2                        2.2             9.2                   127.1  
3                        2.2             9.7                   177.2  
4                        1.5             6.4                   121.8  
...                      ...             ...                     ...  
7106                     1.3             5.1                   191.1  
7107                     1.4             5.8                   221.3  
7108                     1.6             5.2                   227.4  
7109                     1.5             4.6                   199.8  
7110                     1.4             4.1                   186.5  

[7111 rows x 12 columns]

In [4]:
X_full = ds.iloc[:,1:-3]
y_full = ds.iloc[:, -3:]

In [5]:
X_full

deg_C  relative_humidity  absolute_humidity  sensor_1  sensor_2  \
0      13.1               46.0             0.7578    1387.2    1087.8   
1      13.2               45.3             0.7255    1279.1     888.2   
2      12.6               56.2             0.7502    1331.9     929.6   
3      11.0               62.4             0.7867    1321.0     929.0   
4      11.9               59.0             0.7888    1272.0     852.7   
...     ...                ...                ...       ...       ...   
7106    9.2               32.0             0.3871    1000.5     811.2   
7107    9.1               33.2             0.3766    1022.7     790.0   
7108    9.6               34.6             0.4310    1044.4     767.3   
7109    8.0               40.7             0.4085     952.8     691.9   
7110    8.0               41.3             0.4375    1108.8     745.7   

      sensor_3  sensor_4  sensor_5  
0       1056.0    1742.8    1293.4  
1       1197.5    1449.9    1010.9  
2       1060.2    1586.1    1117.0  
3       1102.9    1536.5    1263.2  
4       1180.9    1415.5    1132.2  
...        ...       ...       ...  
7106     873.0     909.0     910.5  
7107     951.6     912.9     903.4  
7108     861.9     889.2    1159.1  
7109     908.5     917.0    1206.3  
7110     797.1     880.0    1273.1  

[7111 rows x 8 columns]

In [6]:
sc = StandardScaler()
X_full = sc.fit_transform(X_full)

In [7]:
X_full

array([[-0.97992726, -0.08972573, -0.88365328, ...,  0.55437357,
         0.65559881,  0.7734103 ],
       [-0.96732861, -0.12996138, -0.96462148, ...,  1.01018627,
        -0.18088625,  0.03293336],
       [-1.04292051,  0.49656516, -0.90270462, ...,  0.56790299,
         0.20808359,  0.31103815],
       ...,
       [-1.42088   , -0.74499202, -1.70286098, ..., -0.07087905,
        -1.78217397,  0.42138888],
       [-1.6224584 , -0.39436708, -1.75926298, ...,  0.07923312,
        -1.70278071,  0.5451075 ],
       [-1.6224584 , -0.35987938, -1.68656707, ..., -0.27961872,
        -1.80844799,  0.72020081]])

In [8]:
type(X_full)

numpy.ndarray

In [9]:
X_full = pd.DataFrame(X_full)

In [10]:
X_full

0         1         2         3         4         5         6  \
0    -0.979927 -0.089726 -0.883653  1.352851  0.531052  0.554374  0.655599   
1    -0.967329 -0.129961 -0.964621  0.858164 -0.176852  1.010186 -0.180886   
2    -1.042921  0.496565 -0.902705  1.099787 -0.030022  0.567903  0.208084   
3    -1.244499  0.852938 -0.811208  1.049907 -0.032150  0.705452  0.066432   
4    -1.131111  0.657508 -0.805944  0.825673 -0.302757  0.956713 -0.279128   
...        ...       ...       ...       ...       ...       ...       ...   
7106 -1.471275 -0.894439 -1.812908 -0.416764 -0.449941 -0.035123 -1.725628   
7107 -1.483873 -0.825463 -1.839228 -0.315172 -0.525129  0.218071 -1.714490   
7108 -1.420880 -0.744992 -1.702861 -0.215869 -0.605637 -0.070879 -1.782174   
7109 -1.622458 -0.394367 -1.759263 -0.635048 -0.873052  0.079233 -1.702781   
7110 -1.622458 -0.359879 -1.686567  0.078838 -0.682244 -0.279619 -1.808448   

             7  
0     0.773410  
1     0.032933  
2     0.311038  
3     0.694251  
4     0.350880  
...        ...  
7106 -0.230231  
7107 -0.248841  
7108  0.421389  
7109  0.545108  
7110  0.720201  

[7111 rows x 8 columns]

In [11]:
y_org = y_full

In [12]:
sc_1 = StandardScaler()
y_org = sc_1.fit_transform(y_org)

In [13]:
y_full = y_org[:,-3]

In [14]:
y_full

array([ 0.28595669,  0.00952411,  0.07863226, ..., -0.3360166 ,
       -0.40512475, -0.47423289])

In [15]:
len(ds)

7111

In [16]:
X = []
y = []
for i in range(6, len(ds)):
    X.append(X_full.iloc[i-6:i, :])
    y.append(y_full[i-6:i,])
    
X = np.array(X)
y = np.array(y)

In [17]:
X.shape

(7105, 6, 8)

In [18]:
X

array([[[-0.97992726, -0.08972573, -0.88365328, ...,  0.55437357,
          0.65559881,  0.7734103 ],
        [-0.96732861, -0.12996138, -0.96462148, ...,  1.01018627,
         -0.18088625,  0.03293336],
        [-1.04292051,  0.49656516, -0.90270462, ...,  0.56790299,
          0.20808359,  0.31103815],
        [-1.24449891,  0.85293805, -0.81120804, ...,  0.70545212,
          0.06643231,  0.69425135],
        [-1.13111106,  0.65750775, -0.80594386, ...,  0.95671284,
         -0.27912826,  0.35087974],
        [-1.21930161,  0.53105285, -0.81597088, ...,  1.71790395,
         -0.14461667, -0.12931628]],

       [[-0.96732861, -0.12996138, -0.96462148, ...,  1.01018627,
         -0.18088625,  0.03293336],
        [-1.04292051,  0.49656516, -0.90270462, ...,  0.56790299,
          0.20808359,  0.31103815],
        [-1.24449891,  0.85293805, -0.81120804, ...,  0.70545212,
          0.06643231,  0.69425135],
        [-1.13111106,  0.65750775, -0.80594386, ...,  0.95671284,
         -0.27

In [19]:
y.shape

(7105, 6)

In [20]:
y

array([[ 0.28595669,  0.00952411,  0.07863226,  0.07863226, -0.40512475,
        -0.61244918],
       [ 0.00952411,  0.07863226,  0.07863226, -0.40512475, -0.61244918,
        -0.61244918],
       [ 0.07863226,  0.07863226, -0.40512475, -0.61244918, -0.61244918,
        -0.75066547],
       ...,
       [-0.68155732, -0.47423289, -0.40512475, -0.61244918, -0.54334104,
        -0.47423289],
       [-0.47423289, -0.40512475, -0.61244918, -0.54334104, -0.47423289,
        -0.3360166 ],
       [-0.40512475, -0.61244918, -0.54334104, -0.47423289, -0.3360166 ,
        -0.40512475]])

In [21]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state=0)

In [22]:
X_train.shape

(5328, 6, 8)

In [40]:
tf.keras.backend.clear_session()
model = tf.keras.models.Sequential([tf.keras.layers.SimpleRNN(64,activation="relu", input_shape = [6,8], return_sequences=True),
                                    tf.keras.layers.SimpleRNN(32, activation = "relu", return_sequences=False),
                                    tf.keras.layers.Dense(1)])
# model = tf.keras.models.Sequential([tf.keras.layers.LSTM(64,activation="relu", input_shape = [6,8], return_sequences=True),
#                                     tf.keras.layers.LSTM(32, activation = "relu", return_sequences=False),
#                                     tf.keras.layers.Dense(1)])

In [41]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="mse")

In [42]:
history = model.fit(X_train, y_train, epochs=20, validation_split=0.2)

Epoch 1/7
134/134 [==============================] - 7s 36ms/step - loss: 0.4842 - accuracy: 0.0000e+00 - val_loss: 0.5028 - val_accuracy: 0.0000e+00
Epoch 2/7
134/134 [==============================] - 5s 34ms/step - loss: 0.4416 - accuracy: 0.0000e+00 - val_loss: 0.4340 - val_accuracy: 0.0000e+00
Epoch 3/7
134/134 [==============================] - 5s 34ms/step - loss: 0.4366 - accuracy: 0.0000e+00 - val_loss: 0.4444 - val_accuracy: 0.0000e+00
Epoch 4/7
134/134 [==============================] - 5s 34ms/step - loss: 0.4350 - accuracy: 0.0000e+00 - val_loss: 0.4524 - val_accuracy: 0.0000e+00
Epoch 5/7
134/134 [==============================] - 5s 34ms/step - loss: 0.4291 - accuracy: 0.0000e+00 - val_loss: 0.4303 - val_accuracy: 0.0000e+00
Epoch 6/7
134/134 [==============================] - 5s 34ms/step - loss: 0.4305 - accuracy: 0.0000e+00 - val_loss: 0.4273 - val_accuracy: 0.0000e+00
Epoch 7/7
134/134 [==============================] - 5s 36ms/step - loss: 0.4186 - accuracy: 0.0000e

In [36]:
model.evaluate(X_valid, y_valid)

56/56 [==============================] - 0s 8ms/step - loss: 0.4084 - accuracy: 0.0000e+00


[0.40839216113090515, 0.0]

In [37]:
model.predict([X_valid[0:6]])

array([[ 1.1208286 ],
       [ 2.0998094 ],
       [-0.34048104],
       [ 0.96061826],
       [-0.3958525 ],
       [ 0.59866315]], dtype=float32)

In [38]:
y_valid[0]

array([ 1.73722771,  1.52990328,  1.46079514,  0.56238927,  0.1477404 ,
       -0.26690846])

In [39]:
X_valid[0:1]

array([[[ 0.01536607,  0.743727  ,  1.17288894,  2.36830825,
          1.82733921, -1.37034792,  1.31045038,  1.9246226 ],
        [ 0.00276742,  0.95640115,  1.19670312,  1.99122984,
          1.89224223, -1.34844314,  0.95032485,  1.72856003],
        [-0.36259343,  1.66914693,  1.17364097,  1.45764558,
          1.30137652, -1.11232249,  0.91177057,  1.18231084],
        [-0.36259343,  1.48521253,  1.15809908,  0.86823175,
          0.47678901, -1.06303674,  0.6892981 ,  0.71233734],
        [-0.09802178,  1.50245638,  1.11448154,  0.46278093,
          0.56900095, -0.84656597,  0.42084609,  0.84523001],
        [-0.07282448,  1.15183144,  1.12626329, -0.25064777,
          0.21469432, -0.70193   , -0.15432664,  0.20121166]]])